In [16]:
import pandas as pd
import config2 as cfg
from sqlalchemy import create_engine

In [17]:
# creating a connection to an aws rds postgres cloud database.
rds_connection_string = f'postgres:{cfg.password}@test-db.cy2enoewwvsi.us-east-2.rds.amazonaws.com:5432/stocks_db'
engine = create_engine(f'postgres://{rds_connection_string}')

In [18]:
# checking out the table names in the database.
engine.table_names()

['sandp', 'avg_sandp', 'sandp_russell', 'new_route', 'sandp2', 'russell_2000']

In [19]:
# checking out the SandP_500 table.
sandp = pd.read_sql_query('SELECT * FROM sandp', con=engine)
sandp.head()

,symbol,name,price_to_bookvalue,price_to_book,price_to_sales,price_to_earnings,receivables_turnover,price_to_free_cash_flow,price_to_operating_cash_flow,enterprise_value_multiple,...,asset_growth,book_value_per_share_growth,debt_growth,randd_expense_growth,sganda_expense_growth,percent_return_on_investment,above_below_sandp_return,market_cap,industry,sector
0,A,"Agilent Technologies, Inc.",2.55170,5.17165,1.48130,6.30885,7.0014,18.1807,13.57995,16.746223,...,0.18005,0.15185,0.31885,-0.0674,0.01880,215.407785,1,7.462700e+09,Medical Diagnostics & Research,Healthcare
1,AAL,"American Airlines Group, Inc.",-99.00000,-99.00000,0.11565,-99.00000,27.3348,-99.0000,2.20925,61.812855,...,-0.00170,-0.06235,0.00975,-99.0000,0.01435,492.976589,1,6.133809e+08,Airlines,Industrials
2,AAP,"Advance Auto Parts, Inc.",2.95660,3.10380,0.70600,14.16840,57.0461,7.4185,5.46130,0.499984,...,0.03670,0.19520,-0.57150,-99.0000,0.10360,158.290852,1,1.912092e+09,Retail - Apparel & Specialty,Consumer Cyclical
3,AAPL,"Apple, Inc.",5.42765,4.62715,3.98235,19.54495,10.0906,17.3279,15.35960,0.493341,...,0.44800,0.44245,-99.00000,0.2694,0.21645,641.441749,1,9.151793e+10,Computer Hardware,Technology
4,ABBV,"AbbVie, Inc.",16.46870,-99.00000,3.01900,10.48360,-99.0000,9.2123,8.74540,0.001609,...,-99.00000,-99.00000,-99.00000,0.4613,0.14080,127.493713,0,6.619065e+10,Drug Manufacturers,Healthcare

In [20]:
# checking out the sandp_russell data.
sandp_russell = pd.read_sql_query('SELECT * FROM sandp_russell', con=engine)
# dropping wierd column that showed up and dont want to do other process.
# sandp_russell = sandp_russell.drop(columns={'Unnamed: 0'})
sandp_russell.head()

,symbol,name,price_to_bookvalue,price_to_book,price_to_sales,price_to_earnings,receivables_turnover,price_to_free_cash_flow,price_to_operating_cash_flow,enterprise_value_multiple,...,asset_growth,book_value_per_share_growth,debt_growth,randd_expense_growth,sganda_expense_growth,percent_return_on_investment,above_below_sandp_return,market_cap,industry,sector
0,A,"Agilent Technologies, Inc.",2.5517,5.17165,1.48130,6.30885,7.0014,18.18070,13.57995,16.746223,...,0.18005,0.15185,0.31885,-0.0674,0.01880,215.407785,1,7.462700e+09,Medical Diagnostics & Research,Healthcare
1,AAL,"American Airlines Group, Inc.",-99.0000,-99.00000,0.11565,-99.00000,27.3348,-99.00000,2.20925,61.812855,...,-0.00170,-0.06235,0.00975,-99.0000,0.01435,492.976589,1,6.133809e+08,Airlines,Industrials
2,AAN,"Aaron's, Inc.",1.5315,1.95610,0.78855,12.37860,27.7757,59.12785,19.92670,0.126805,...,0.10410,0.12870,-0.38070,-99.0000,0.08135,153.807704,1,5.597095e+08,Consulting & Outsourcing,Industrials
3,AAON,"AAON, Inc.",3.4176,3.41760,1.63730,16.86505,6.7351,20.69945,10.96230,0.287753,...,0.06795,0.13045,-0.98780,-99.0000,-0.02605,454.948301,1,3.842042e+08,Building Materials,Basic Materials
4,AAP,"Advance Auto Parts, Inc.",2.9566,3.10380,0.70600,14.16840,57.0461,7.41850,5.46130,0.499984,...,0.03670,0.19520,-0.57150,-99.0000,0.10360,158.290852,1,1.912092e+09,Retail - Apparel & Specialty,Consumer Cyclical

In [21]:
# checking out the russell_2000 data.
russell = pd.read_sql_query('SELECT * FROM russell_2000', con=engine)
russell.head()

Empty DataFrame
Columns: [symbol, name, price_to_bookvalue, price_to_book, price_to_sales, price_to_earnings, receivables_turnover, price_to_free_cash_flow, price_to_operating_cash_flow, enterprise_value_multiple, gross_profit_margin, pretax_profit_margin, net_profit_margin, tax_rate, return_on_assets, return_on_equity, return_on_capital_employed, receivables_turnover_1, payables_turnover, inventory_turnover, fixed_asset_turnover, asset_turnover, current_ratio, quick_ratio, cash_ratio, days_of_sales_outstanding, days_of_inventory_outstanding, operating_cycle, days_of_payables_outstanding, cash_conversion_cycle, debt_ratio, debt_to_equity_ratio, longterm_debt_to_capitalization, total_debt_to_capitalization, interest_coverage, cash_flow_to_debt, company_equity_multiplier, operating_cash_flow_per_share, free_cash_flow_per_share, cash_per_share, payout_ratio, receivables_turnover_2, operating_cash_flow_to_sales, free_cash_flow_to_operating_cash_flow, cash_flow_coverage_ratio, short_term_coverage_ratio, capital_expenditure_coverage_ratio, dividend_capex_coverage_ratio, dividend_payout_ratio, gross_profit_growth, ebit_growth, operating_income_growth, net_income_growth, eps_growth, eps_diluted_growth, weighted_average_share_growth, weighted_averages_shares_diluted_growth, dividents_per_share_growth, operating_cash_flow_growth, free_cash_flow_growth, ten_year_revenue_growth_per_share, five_year_revenue_growth_per_share, three_year_revenue_growth_per_share, ten_year_operating_cf_growth_per_share, five_year_operating_cf_growth_per_share, three_year_operating_cf_growth_per_share, ten_year_net_income_growth_per_share, five_year_net_income_growth_per_share, three_year_net_income_growth_per_share, ten_year_shareholders_equity_growth_per_share, five_year_shareholders_equity_growth_per_share, three_year_shareholders_equity_growth_per_share, ten_year_dividend_growth_per_share, five_year_dividend_growth_per_share, three_year_dividend_growth_per_share, receivables_growh, inventory_growth, asset_growth, book_value_per_share_growth, debt_growth, randd_expense_growth, sganda_expense_growth, percent_return_on_investment, above_below_sandp_return]
Index: []

[0 rows x 84 columns]

In [22]:
# checking out the new_route data.
new_route = pd.read_sql_query('SELECT * FROM new_route', con=engine)
new_route.head()

,symbol,name,Revenue,Revenue_Growth,Cost_of_Revenue,Gross_Profit,RandD_Expenses,SGandA_Expense,Operating_Expenses,Operating_Income,...,Issuance_buybacks_shares,Dividend_payments,Financing_Cash_Flow,Effect_forex_changes_on_cash,Net_cash_flow_Change_cash,Free_Cash_Flow,Net_Cash_to_Marketcap,market_cap,percent_return_on_investment,above_below_sandp_return
0,A,"Agilent Technologies, Inc.",4.962500e+09,-0.004496,2.351500e+09,2.611000e+09,6.270000e+08,1.677500e+09,2.304500e+09,3.065000e+08,...,-9.900000e+07,-99.0,6.290000e+08,24000000.0,622000000.0,4.425000e+08,0.12275,7.462700e+09,215.407785,1
1,AAL,"American Airlines Group, Inc.",9.958500e+09,-0.581000,5.015500e+09,4.943000e+09,-9.900000e+01,3.403500e+09,5.445000e+09,-5.020000e+08,...,2.065000e+08,-99.0,8.775000e+08,-99.0,-19000000.0,-2.575000e+08,-2.12480,6.133809e+08,492.976589,1
2,AAP,"Advance Auto Parts, Inc.",5.412623e+09,0.052600,2.768397e+09,2.644226e+09,-9.900000e+01,2.189841e+09,2.189841e+09,4.543850e+08,...,-6.466000e+07,-22803000.0,-4.514910e+08,-99.0,62660000.0,5.141510e+08,-0.02730,1.912092e+09,158.290852,1
3,AAPL,"Apple, Inc.",5.406500e+10,0.332310,3.261200e+10,2.145300e+10,1.557500e+09,4.833000e+09,6.390500e+09,1.506250e+10,...,-4.937000e+09,-99.0,9.600000e+08,-99.0,-307000000.0,1.276800e+10,0.07035,9.151793e+10,641.441749,1
4,ABBV,"AbbVie, Inc.",1.492610e+10,0.050084,4.174695e+09,1.075140e+10,2.101220e+09,3.584286e+09,5.927006e+09,4.824397e+09,...,-9.900000e+01,-99.0,-2.408076e+09,-99.0,4915000.0,4.791386e+09,-0.13870,6.619065e+10,127.493713,0

In [23]:
# sandp returned about 146 from 2009/2010 to 2018/2019.

In [24]:
dataframes = [sandp, sandp_russell, russell, new_route]
for df in dataframes:
    above_below_sandp = []
    for returns in df['percent_return_on_investment']:
        if returns > 228:
            above_below_sandp.append(1)

        else:
            above_below_sandp.append(0)

    df['above_below_sandp_return'] = above_below_sandp

In [25]:
sandp.head()

,symbol,name,price_to_bookvalue,price_to_book,price_to_sales,price_to_earnings,receivables_turnover,price_to_free_cash_flow,price_to_operating_cash_flow,enterprise_value_multiple,...,asset_growth,book_value_per_share_growth,debt_growth,randd_expense_growth,sganda_expense_growth,percent_return_on_investment,above_below_sandp_return,market_cap,industry,sector
0,A,"Agilent Technologies, Inc.",2.55170,5.17165,1.48130,6.30885,7.0014,18.1807,13.57995,16.746223,...,0.18005,0.15185,0.31885,-0.0674,0.01880,215.407785,0,7.462700e+09,Medical Diagnostics & Research,Healthcare
1,AAL,"American Airlines Group, Inc.",-99.00000,-99.00000,0.11565,-99.00000,27.3348,-99.0000,2.20925,61.812855,...,-0.00170,-0.06235,0.00975,-99.0000,0.01435,492.976589,1,6.133809e+08,Airlines,Industrials
2,AAP,"Advance Auto Parts, Inc.",2.95660,3.10380,0.70600,14.16840,57.0461,7.4185,5.46130,0.499984,...,0.03670,0.19520,-0.57150,-99.0000,0.10360,158.290852,0,1.912092e+09,Retail - Apparel & Specialty,Consumer Cyclical
3,AAPL,"Apple, Inc.",5.42765,4.62715,3.98235,19.54495,10.0906,17.3279,15.35960,0.493341,...,0.44800,0.44245,-99.00000,0.2694,0.21645,641.441749,1,9.151793e+10,Computer Hardware,Technology
4,ABBV,"AbbVie, Inc.",16.46870,-99.00000,3.01900,10.48360,-99.0000,9.2123,8.74540,0.001609,...,-99.00000,-99.00000,-99.00000,0.4613,0.14080,127.493713,0,6.619065e+10,Drug Manufacturers,Healthcare

In [26]:
sandp_russell.head()

,symbol,name,price_to_bookvalue,price_to_book,price_to_sales,price_to_earnings,receivables_turnover,price_to_free_cash_flow,price_to_operating_cash_flow,enterprise_value_multiple,...,asset_growth,book_value_per_share_growth,debt_growth,randd_expense_growth,sganda_expense_growth,percent_return_on_investment,above_below_sandp_return,market_cap,industry,sector
0,A,"Agilent Technologies, Inc.",2.5517,5.17165,1.48130,6.30885,7.0014,18.18070,13.57995,16.746223,...,0.18005,0.15185,0.31885,-0.0674,0.01880,215.407785,0,7.462700e+09,Medical Diagnostics & Research,Healthcare
1,AAL,"American Airlines Group, Inc.",-99.0000,-99.00000,0.11565,-99.00000,27.3348,-99.00000,2.20925,61.812855,...,-0.00170,-0.06235,0.00975,-99.0000,0.01435,492.976589,1,6.133809e+08,Airlines,Industrials
2,AAN,"Aaron's, Inc.",1.5315,1.95610,0.78855,12.37860,27.7757,59.12785,19.92670,0.126805,...,0.10410,0.12870,-0.38070,-99.0000,0.08135,153.807704,0,5.597095e+08,Consulting & Outsourcing,Industrials
3,AAON,"AAON, Inc.",3.4176,3.41760,1.63730,16.86505,6.7351,20.69945,10.96230,0.287753,...,0.06795,0.13045,-0.98780,-99.0000,-0.02605,454.948301,1,3.842042e+08,Building Materials,Basic Materials
4,AAP,"Advance Auto Parts, Inc.",2.9566,3.10380,0.70600,14.16840,57.0461,7.41850,5.46130,0.499984,...,0.03670,0.19520,-0.57150,-99.0000,0.10360,158.290852,0,1.912092e+09,Retail - Apparel & Specialty,Consumer Cyclical

In [27]:
russell.head()

Empty DataFrame
Columns: [symbol, name, price_to_bookvalue, price_to_book, price_to_sales, price_to_earnings, receivables_turnover, price_to_free_cash_flow, price_to_operating_cash_flow, enterprise_value_multiple, gross_profit_margin, pretax_profit_margin, net_profit_margin, tax_rate, return_on_assets, return_on_equity, return_on_capital_employed, receivables_turnover_1, payables_turnover, inventory_turnover, fixed_asset_turnover, asset_turnover, current_ratio, quick_ratio, cash_ratio, days_of_sales_outstanding, days_of_inventory_outstanding, operating_cycle, days_of_payables_outstanding, cash_conversion_cycle, debt_ratio, debt_to_equity_ratio, longterm_debt_to_capitalization, total_debt_to_capitalization, interest_coverage, cash_flow_to_debt, company_equity_multiplier, operating_cash_flow_per_share, free_cash_flow_per_share, cash_per_share, payout_ratio, receivables_turnover_2, operating_cash_flow_to_sales, free_cash_flow_to_operating_cash_flow, cash_flow_coverage_ratio, short_term_coverage_ratio, capital_expenditure_coverage_ratio, dividend_capex_coverage_ratio, dividend_payout_ratio, gross_profit_growth, ebit_growth, operating_income_growth, net_income_growth, eps_growth, eps_diluted_growth, weighted_average_share_growth, weighted_averages_shares_diluted_growth, dividents_per_share_growth, operating_cash_flow_growth, free_cash_flow_growth, ten_year_revenue_growth_per_share, five_year_revenue_growth_per_share, three_year_revenue_growth_per_share, ten_year_operating_cf_growth_per_share, five_year_operating_cf_growth_per_share, three_year_operating_cf_growth_per_share, ten_year_net_income_growth_per_share, five_year_net_income_growth_per_share, three_year_net_income_growth_per_share, ten_year_shareholders_equity_growth_per_share, five_year_shareholders_equity_growth_per_share, three_year_shareholders_equity_growth_per_share, ten_year_dividend_growth_per_share, five_year_dividend_growth_per_share, three_year_dividend_growth_per_share, receivables_growh, inventory_growth, asset_growth, book_value_per_share_growth, debt_growth, randd_expense_growth, sganda_expense_growth, percent_return_on_investment, above_below_sandp_return]
Index: []

[0 rows x 84 columns]

In [28]:
new_route.head()

,symbol,name,Revenue,Revenue_Growth,Cost_of_Revenue,Gross_Profit,RandD_Expenses,SGandA_Expense,Operating_Expenses,Operating_Income,...,Issuance_buybacks_shares,Dividend_payments,Financing_Cash_Flow,Effect_forex_changes_on_cash,Net_cash_flow_Change_cash,Free_Cash_Flow,Net_Cash_to_Marketcap,market_cap,percent_return_on_investment,above_below_sandp_return
0,A,"Agilent Technologies, Inc.",4.962500e+09,-0.004496,2.351500e+09,2.611000e+09,6.270000e+08,1.677500e+09,2.304500e+09,3.065000e+08,...,-9.900000e+07,-99.0,6.290000e+08,24000000.0,622000000.0,4.425000e+08,0.12275,7.462700e+09,215.407785,0
1,AAL,"American Airlines Group, Inc.",9.958500e+09,-0.581000,5.015500e+09,4.943000e+09,-9.900000e+01,3.403500e+09,5.445000e+09,-5.020000e+08,...,2.065000e+08,-99.0,8.775000e+08,-99.0,-19000000.0,-2.575000e+08,-2.12480,6.133809e+08,492.976589,1
2,AAP,"Advance Auto Parts, Inc.",5.412623e+09,0.052600,2.768397e+09,2.644226e+09,-9.900000e+01,2.189841e+09,2.189841e+09,4.543850e+08,...,-6.466000e+07,-22803000.0,-4.514910e+08,-99.0,62660000.0,5.141510e+08,-0.02730,1.912092e+09,158.290852,0
3,AAPL,"Apple, Inc.",5.406500e+10,0.332310,3.261200e+10,2.145300e+10,1.557500e+09,4.833000e+09,6.390500e+09,1.506250e+10,...,-4.937000e+09,-99.0,9.600000e+08,-99.0,-307000000.0,1.276800e+10,0.07035,9.151793e+10,641.441749,1
4,ABBV,"AbbVie, Inc.",1.492610e+10,0.050084,4.174695e+09,1.075140e+10,2.101220e+09,3.584286e+09,5.927006e+09,4.824397e+09,...,-9.900000e+01,-99.0,-2.408076e+09,-99.0,4915000.0,4.791386e+09,-0.13870,6.619065e+10,127.493713,0

In [29]:
# uploading sandp to postgres.
sandp.to_sql(name='sandp', con=engine, if_exists='replace', index=False)

In [30]:
# uploading russell to postgres.
russell.to_sql(name='russell_2000', con=engine, if_exists='replace', index=False)

In [31]:
# uploading sandp_russell to postgres.
sandp_russell.to_sql(name='sandp_russell', con=engine, if_exists='replace', index=False)

In [32]:
# uploading new_route to postgres.
new_route.to_sql(name='new_route', con=engine, if_exists='replace', index=False)